In [54]:
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv(r"C:\Users\Finayon\Documents\data analysis\udemy\programming language popularity\QueryResults.csv", names = ['DATE', 'TAG', 'POSTS'], header = 0)
df

                     DATE         TAG  POSTS
0     2008-07-01 00:00:00          c#      3
1     2008-08-01 00:00:00    assembly      8
2     2008-08-01 00:00:00  javascript    162
3     2008-08-01 00:00:00           c     85
4     2008-08-01 00:00:00      python    124
...                   ...         ...    ...
1986  2020-07-01 00:00:00           r   5694
1987  2020-07-01 00:00:00          go    743
1988  2020-07-01 00:00:00        ruby    775
1989  2020-07-01 00:00:00        perl    182
1990  2020-07-01 00:00:00       swift   3607

[1991 rows x 3 columns]

In [43]:
#adjust the date
pd.to_datetime(df['DATE'])

0      2008-07-01
1      2008-08-01
2      2008-08-01
3      2008-08-01
4      2008-08-01
          ...
1986   2020-07-01
1987   2020-07-01
1988   2020-07-01
1989   2020-07-01
1990   2020-07-01
Name: DATE, Length: 1991, dtype: datetime64[ns]

In [44]:
#Which programming language had the most number of posts since the creation of Stack Overflow?
df.groupby('TAG').sum()

                                                         DATE    POSTS
TAG
assembly    2008-08-01 00:00:002008-09-01 00:00:002008-10-...    34852
c           2008-08-01 00:00:002008-09-01 00:00:002008-10-...   336042
c#          2008-07-01 00:00:002008-08-01 00:00:002008-09-...  1423530
c++         2008-08-01 00:00:002008-09-01 00:00:002008-10-...   684210
delphi      2008-08-01 00:00:002008-09-01 00:00:002008-10-...    46212
go          2009-11-01 00:00:002009-12-01 00:00:002010-01-...    47499
java        2008-08-01 00:00:002008-09-01 00:00:002008-10-...  1696403
javascript  2008-08-01 00:00:002008-09-01 00:00:002008-10-...  2056510
perl        2008-08-01 00:00:002008-09-01 00:00:002008-10-...    65286
php         2008-08-01 00:00:002008-09-01 00:00:002008-10-...  1361988
python      2008-08-01 00:00:002008-09-01 00:00:002008-10-...  1496210
r           2008-09-01 00:00:002008-11-01 00:00:002008-12-...   356799
ruby        2008-08-01 00:00:002008-09-01 00:00:002008-10-...   214582
swift       2009-01-01 00:00:002009-02-01 00:00:002009-03-...   273055

In [45]:
#how many months of entries exist per programming language.
df.groupby('TAG').count()

            DATE  POSTS
TAG
assembly     144    144
c            144    144
c#           145    145
c++          144    144
delphi       144    144
go           129    129
java         144    144
javascript   144    144
perl         144    144
php          144    144
python       144    144
r            142    142
ruby         144    144
swift        135    135

In [49]:
reshaped_df = df.pivot(index='DATE', columns='TAG', values='POSTS')
reshaped_df

TAG,assembly,c,c#,c++,delphi,go,java,javascript,perl,php,python,r,ruby,swift
DATE,,,,,,,,,,,,,,
2008-07-01 00:00:00,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008-08-01 00:00:00,8.0,85.0,511.0,164.0,14.0,NaN,222.0,162.0,28.0,161.0,124.0,NaN,73.0,NaN
2008-09-01 00:00:00,28.0,321.0,1649.0,755.0,105.0,NaN,1137.0,640.0,131.0,482.0,542.0,6.0,290.0,NaN
2008-10-01 00:00:00,15.0,303.0,1989.0,811.0,112.0,NaN,1153.0,725.0,127.0,617.0,510.0,NaN,249.0,NaN
2008-11-01 00:00:00,17.0,259.0,1730.0,735.0,141.0,NaN,958.0,579.0,97.0,504.0,452.0,1.0,160.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-03-01 00:00:00,317.0,2670.0,8954.0,5107.0,181.0,719.0,13253.0,20483.0,215.0,6672.0,26673.0,5761.0,780.0,3434.0
2020-04-01 00:00:00,406.0,3472.0,10042.0,6820.0,250.0,887.0,15377.0,24634.0,240.0,8060.0,32605.0,7047.0,860.0,4015.0
2020-05-01 00:00:00,386.0,3602.0,9923.0,7063.0,221.0,826.0,14711.0,25196.0,228.0,7917.0,34478.0,6833.0,774.0,4066.0
2020-06-01 00:00:00,363.0,2757.0,9064.0,6161.0,214.0,765.0,13015.0,23360.0,203.0,7188.0,31817.0,6249.0,670.0,3733.0
2020-07-01 00:00:00,298.0,2294.0,9145.0,5756.0,212.0,743.0,12723.0,23802.0,182.0,7334.0,31261.0,5694.0,775.0,3607.0

In [51]:
reshaped_df.fillna(0, inplace = True)
reshaped_df.isna().values.any()

np.False_